### ISSUE TITLE
meson: postgres flex wrapper

### ISSUE THREAD

**Issue by anarazel** [anarazel/postgres#50]
In the autoconf build we do some additional error checking, and fix warnings with some older flex versions:
```
%.c: %.l
ifdef FLEX
	$(FLEX) $(if $(FLEX_NO_BACKUP),-b) $(FLEXFLAGS) -o'$@' $<
	@$(if $(FLEX_NO_BACKUP),if [ `wc -l <lex.backup` -eq 1 ]; then rm lex.backup; else echo "Scanner requires backup; see lex.backup." 1>&2; exit 1; fi)
	$(if $(FLEX_FIX_WARNING),$(PERL) $(top_srcdir)/src/tools/fix-old-flex-code.pl '$@')
else
	@$(missing) flex $< '$@'
endif
```
That's not yet implemented for meson. The best way to do so would be a small python wrapper around bison, doing these checks, I think. I.e. have two options controlling the FLEX_NO_BACKUP and FLEX_FIX_WARNING behaviour, and pass on all remaining options.

**Comment by eli-schwartz** [comment]
Wouldn't it be a better idea, perhaps, to have a configure check for the version of flex, and if it's too old, create an intermediate rule to run `fix-old-flex-code.pl` and produce a new source file for use by the flex rule itself?

**Comment by anarazel** [comment]
> Wouldn't it be a better idea, perhaps, to have a configure check for the version of flex, and if it's too old, create an intermediate rule to run fix-old-flex-code.pl and produce a new source file for use by the flex rule itself?

There's 13 .l files PG - I don't quite see how to do that in meson without a lot of duplication, due to not having "functions" and the restrictions around output directories of targets?

Separately, the FLEX_NO_BACKUP bit has to happen regardless of the flex version, that's ensuring that we didn't do something to make the lexer inefficient - and that's actually not nice to do with meson, afaics, because it'd be a target that doesn't generate anything, making the dependency rules complicated.
