### ISSUE TITLE
No need to set library_path_var for netbsd

### ISSUE THREAD

**Issue by nbyavuz** [anarazel/postgres#56]
We are setting library_path_var for netbsd but that shouldn't be needed. Related commit: https://github.com/anarazel/postgres/pull/26/commits/76c88356f4c945f15a5b24b174570853b3dbd98b

**Comment by anarazel** [comment]
I've since figured out why it's needed (netbsd patched their meson in a broken way), documented that in meson.build to be separate from the reasoning for openbsd. Relevant netbsd bug: http://gnats.netbsd.org/56959
