### ISSUE TITLE
NEED SOME HELP WITH POSTGRESQL RAW QUERIES

### ISSUE THREAD

**Issue by HardikSheth1717** [anarazel/postgres#83]
Hello,

I am working as a Technical Lead in a product-based company. We are using PostgreSQL as our product's database. We were using an ORM to communicate and querying the database. But now we want to use raw queries. I am facing some issues with conditional statements in raw queries. Let me show an example:

![image](https://github.com/anarazel/postgres/assets/12509977/55061670-bf26-4111-94d4-f2518b4c1e15)

Now, here I have written a very simple IF statement just like used to write in MS SQL Server. But above code shows me below error:

![image](https://github.com/anarazel/postgres/assets/12509977/5d3dd7c8-7a95-41c5-925d-e39c24bec83f)

I searched a lot on the internet but couldn't find any solution. As per my understanding, if I want to use SELECT statement in the IF statement then I have to use IF statement inside the function.

Kindly, help me in this because I stuck in this issue from last 4 days. This is very basic requirement which I was using in MS SQL Server very easily. [Here is an example of what I want.](https://learn.microsoft.com/en-us/sql/t-sql/language-elements/if-else-transact-sql?view=sql-server-ver16#examples--and-)

**Comment by anarazel** [comment]
I do not have the resources to help individuals, sorry.  Please ask on the public postgres mailing lists. There also is a slack channel.
